---
title: "Packages"
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## <i class="bi-house-heart"></i> Core

<div class="grid-container-package">
  <div class="grid-item-package">
  <h3><a href="https://github.com/mlr-org/mlr3">mlr3</a> <i class="bi-circle-fill status-stable"></i></h3>
  Basic building blocks for machine learning.
  </div>
  <div class="grid-item-package">
  <h3><a href="https://github.com/mlr-org/mlr3verse">mlr3verse</a> <i class="bi-circle-fill status-stable"></i></h3>
  Meta-package for installing and using core mlr3 packages.
  </div>
</div> 

## <i class="bi-sliders"></i> Optimization 

<div class="grid-container-package">
  <div class="grid-item-package">
  <h3><a href="https://github.com/mlr-org/bbotk">bbotk</a> <i class="bi-circle-fill status-stable"></i></h3>
  Black-box optimization toolkit.
  </div>
  <div class="grid-item-package">
  <h3><a href="https://github.com/mlr-org/paradox">paradox</a> <i class="bi-circle-fill status-stable"></i></h3>
  Universal parameter space description and tools.
  </div>
  <div class="grid-item-package">
  <h3><a href="https://github.com/mlr-org/mlr3tuning">mlr3tuning</a> <i class="bi-circle-fill status-stable"></i></h3>
  Hyperparameter tuning.
  </div>
  <div class="grid-item-package">
  <h3><a href="https://github.com/mlr-org/mlr3hyperband">mlr3hyperband</a> <i class="bi-circle-fill status-stable"></i></h3>
  Adds hyperband optimization to mlr3tuning.
  </div>
  <div class="grid-item-package">
  <h3><a href="https://github.com/mlr-org/mlr3mbo">mlr3mbo</a> <i class="bi-circle-fill status-maturing"></i></h3>
  Adds model-based optimization to mlr3tuning.
  </div>
  <div class="grid-item-package">
  <h3><a href="https://github.com/mlr-org/miesmuschel">miesmuschel</a> <i class="bi-circle-fill status-maturing"></i></h3>
  Adds flexible mixed integer evolutionary strategies.
  </div>
  <div class="grid-item-package">
  <h3><a href="https://github.com/mlr-org/mlr3tuningspaces">mlr3tuningspaces</a> <i class="bi-circle-fill status-stable"></i></h3>
  Collection of search spaces for hyperparameter tuning.
  </div>
  <div class="grid-item-package">
  <h3><a href="https://github.com/mlr-org/mlr3automl">mlr3automl</a> <i class="bi-circle-fill status-maturing"></i></h3>
  Automated Machine Learning.
  </div>
</div> 

## <i class="bi-funnel"></i> Feature Selection

<div class="grid-container-package">
 
  <div class="grid-item-package">
  <h3><a href="https://github.com/mlr-org/mlr3filters">mlr3filters</a> <i class="bi-circle-fill status-stable"></i></h3>
  Filter feature selection.
  </div>
  <div class="grid-item-package">
  <h3><a href="https://github.com/mlr-org/mlr3fselect">mlr3fselect</a> <i class="bi-circle-fill status-stable"></i></h3>
  Wrapper feature selection.
  </div>
</div> 

## <i class="bi-hdd"></i> Data

<div class="grid-container-package">
  <div class="grid-item-package">
  <h3><a href="https://github.com/mlr-org/mlr3db">mlr3db</a> <i class="bi-circle-fill status-stable"></i></h3>
  Data backend to transparently work with databases.
  </div>
  <div class="grid-item-package">
  <h3><a href="https://github.com/mlr-org/mlr3oml">mlr3oml</a> <i class="bi-circle-fill status-stable"></i></h3>
  Connector to OpenML.
  </div>
  <div class="grid-item-package">
  <h3><a href="https://github.com/mlr-org/mlr3data">mlr3data</a> <i class="bi-circle-fill status-stable"></i></h3>
  Additional data sets and tasks.
  </div>
</div>

## <i class="bi-pen"></i> Learners

<div class="grid-container-package">
  <div class="grid-item-package">
  <h3><a href="https://github.com/mlr-org/mlr3learners">mlr3learners</a> <i class="bi-circle-fill status-stable"></i></h3>
  Essential learners for mlr3, maintained by the mlr-org team.
  </div>
  <div class="grid-item-package">
  <h3><a href="https://github.com/mlr-org/mlr3extralearners">mlr3extralearners</a> <i class="bi-circle-fill status-stable"></i></h3>
  Extra learners for mlr3, implemented by the community.
  </div>
  <div class="grid-item-package">
  <h3><a href="https://github.com/mlr-org/mlr3keras">mlr3keras</a> <i class="bi-circle-fill status-maturing"></i></h3>
  Deep learning via keras.
  </div>
</div>

## <i class="bi-bar-chart-line"></i> Visualization

<div class="grid-container-package">
  <div class="grid-item-package">
  <h3><a href="https://github.com/mlr-org/mlr3viz">mlr3viz</a> <i class="bi-circle-fill status-stable"></i></h3>
  Visualizations for tasks, predictions, resample results and benchmarks.
  </div>
</div>

## <i class="bi-share"></i> Pipelines

<div class="grid-container-package">
  <div class="grid-item-package">
  <h3><a href="https://github.com/mlr-org/mlr3pipelines">mlr3pipelines</a> <i class="bi-circle-fill status-stable"></i></h3>
   Dataflow programming toolkit.
  </div>
</div>

## <i class="bi-list-task"></i> Tasks

<div class="grid-container-package">
  <div class="grid-item-package">
  <h3><a href="https://github.com/mlr-org/mlr3spatiotempcv">mlr3spatiotempcv</a> <i class="bi-circle-fill status-stable"></i></h3>
  Spatiotemporal resampling and visualization methods.
  </div>
  <div class="grid-item-package">
  <h3><a href="https://github.com/mlr-org/mlr3cluster">mlr3cluster</a> <i class="bi-circle-fill status-stable"></i></h3>
  Cluster analysis.
  </div>
  <div class="grid-item-package">
  <h3><a href="https://github.com/mlr-org/mlr3proba">mlr3proba</a> <i class="bi-circle-fill status-stable"></i></h3>
  Toolkit for making probabilistic predictions.
  </div>
  <div class="grid-item-package">
  <h3><a href="https://github.com/mlr-org/mlr3ordinal">mlr3ordinal</a> <i class="bi-circle-fill status-maturing"></i></h3>
  Ordinal regression.
  </div>
  <div class="grid-item-package">
  <h3><a href="https://github.com/mlr-org/mlr3multioutput">mlr3multioutput</a> <i class="bi-circle-fill status-maturing"></i></h3>
  Storing and working with multi-output tasks.
  </div>
  <div class="grid-item-package">
  <h3><a href="https://github.com/mlr-org/mlr3temporal">mlr3temporal</a> <i class="bi-circle-fill status-maturing"></i></h3>
  Time series analysis.
  </div>
  <div class="grid-item-package">
  <h3><a href="https://github.com/mlr-org/mlr3spatial">mlr3spatial</a> <i class="bi-circle-fill status-maturing"></i></h3>
  Methods for spatial objects.
  </div>
</div>

## <i class="bi-balloon"></i> Utilities 

<div class="grid-container-package">
  <div class="grid-item-package">
  <h3><a href="https://github.com/mlr-org/mlr3misc">mlr3misc</a> <i class="bi-circle-fill status-stable"></i></h3>
  Miscellaneous helper functions.
  </div>
  <div class="grid-item-package">
  <h3><a href="https://github.com/mlr-org/mlr3measures">mlr3measures</a> <i class="bi-circle-fill status-stable"></i></h3>
  Performance measures for supervised learning.
  </div>
  <div class="grid-item-package">
  <h3><a href="https://github.com/mlr-org/mlr3benchmark">mlr3benchmark</a> <i class="bi-circle-fill status-stable"></i></h3>
  Analysis and tools for benchmarking.
  </div>
  <div class="grid-item-package">
  <h3><a href="https://github.com/mlr-org/mlr3fairness">mlr3fairness</a> <i class="bi-circle-fill status-maturing"></i></h3>
  Machine learning fairness.
  </div>
  <div class="grid-item-package">
  <h3><a href="https://github.com/mlr-org/mlr3batchmark">mlr3batchmark</a> <i class="bi-circle-fill status-maturing"></i></h3>
  Connector between mlr3 and batchtools.
  </div>
</div>
