---
title: "Resources"
site: distill::distill_website
---

# General

-   We *started* writing a [book](https://mlr3book.mlr-org.com/). This
    should be the central entry point to the package.
-   The [mlr3gallery](https://mlr3gallery.mlr-org.com) has some case
    studies and demonstrates how frequently occurring problems can be
    solved. It is still in early days so stay tuned for more to come.
-   [Reference manual](https://mlr3.mlr-org.com/reference/)
-   [FAQ](https://github.com/mlr-org/mlr3/wiki/FAQ)
-   Ask questions on [Stackoverflow (tag
    \#mlr3)](https://stackoverflow.com/questions/tagged/mlr3)
-   **Extension Learners**
    -   Recommended core regression, classification, and survival
        learners are in
        [mlr3learners](https://github.com/mlr-org/mlr3learners)
    -   All others are in
        [mlr3extralearners](https://github.com/mlr-org/mlr3extralearners)
    -   Use the [learner
        search](https://mlr3extralearners.mlr-org.com/articles/learners/list_learners.html)
        to get a simple overview
    -   Use the [learner
        status](https://mlr3extralearners.mlr-org.com/articles/learners/learner_status.html)
        to see their build status
-   **Cheatsheets**
    -   [Overview of cheatsheets](https://cheatsheets.mlr-org.com)
    -   [mlr3](https://cheatsheets.mlr-org.com/mlr3.pdf)
    -   [mlr3tuning](https://cheatsheets.mlr-org.com/mlr3tuning.pdf)
    -   [mlr3pipelines](https://cheatsheets.mlr-org.com/mlr3pipelines.pdf)
-   **Videos**:
    -   [useR2019 talk on
        mlr3](https://www.youtube.com/watch?v=wsP2hiFnDQs)
    -   [useR2019 talk on mlr3pipelines and
        mlr3tuning](https://www.youtube.com/watch?v=gEW5RxkbQuQ)
    -   [useR2020 tutorial on mlr3, mlr3tuning and
        mlr3pipelines](https://www.youtube.com/watch?v=T43hO2o_nZw)
    -   [Recorded talk about mlr3spatiotempcv and mlr3spatial at
        OpenDataScience Europe Conference 2021 in Wageningen,
        NL](https://av.tib.eu/media/55271)
-   **Courses/Lectures**
    -   The course [Introduction to Machine learning
        (I2ML)](https://introduction-to-machine-learning.netlify.app/)
        is a free and open flipped classroom course on the basics of
        machine learning. `mlr3` is used in the
        [demos](https://github.com/slds-lmu/lecture_i2ml/tree/master/code-demos-pdf)
        and
        [exercises](https://github.com/slds-lmu/lecture_i2ml/tree/master/exercises).
-   **Templates/Tutorials**
    -   [mlr3-learndrake](https://github.com/mlr-org/mlr3-learndrake):
        Shows how to use mlr3 with
        [drake](https://docs.ropensci.org/drake/) for reproducible ML
        workflow automation.
-   [List of extension
    packages](https://github.com/mlr-org/mlr3/wiki/Extension-Packages)
-   [mlr-outreach](https://github.com/mlr-org/mlr-outreach) contains
    public talks and slides resources.
-   Our [blog](https://mlr-org.com/) about *mlr* and *mlr3*. (We are not
    the most frequent bloggers ;) )
-   [Wiki](https://github.com/mlr-org/mlr3/wiki): Contains mainly
    information for developers.